# This file contains values from Cookiecutter

default_context:
  project_name: "gpt-chatter"
  project_description: "Awesome `gpt-chatter` is a Python cli/package created with https://github.com/TezRomacH/python-package-template"
  organization: "gpt-chatter"
  license: "MIT"
  minimal_python_version: 3.7
  github_name: "gpt_chatter"
  email: "hello@gpt-chatter.com"
  version: "0.1.0"
  line_length: "88"
  create_example_template: "cli"
